### PR TITLE
Cardio page - dynamic history

### PR DESCRIPTION
**Pull request by prudentprogrammer27**
bugs present:

trying to submit a new entry returns this message to console: 

 page.js:121 Posting error:  SyntaxError: Unexpected end of JSON input
    at eval (page.js:115:25)

### CODE REVIEW

**Review by JoshT1984 — DISMISSED** [review]
Looks good.

**Comment by anthonymeadows** [comment]
use command line to merge with main before next PR

**Review by dave-rob — APPROVED** [review]
Solid

**Review by Mslonoff — APPROVED** [review]

**Review by JoshT1984 — APPROVED** [review]
Looks good!

**Review by Mslonoff — APPROVED** [review]

**Pull request merged**
